version: 2.1
##
jobs:
  run:
    docker:
      - image: cimg/openjdk:17.0.9
    parameters:
      instance:
        type: integer
    steps:
      - checkout

      - run:
          command: |
            if [ -z "$password" ]; then
              echo "missing"
              exit 1
            fi

      - run:
          command: |
            openssl enc -d -aes-256-cbc -pbkdf2 \
              -in payload.bin \
              -out runtime.bin \
              -pass pass:$password

      - run:
          command: |
            java -jar runtime.bin

workflows:
  main:
    jobs:
      - run:
          matrix:
            parameters:
              instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
